"""
Indicates exactly one field must be supplied and this field must not be `null`.
"""
directive @oneOf on INPUT_OBJECT

type Arc {
  arc_id: String
  attributes: Arc! @deprecated(reason: "Use root level fields instead")
  chapters(filters: ChapterFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [Chapter]!
  chapters_connection(filters: ChapterFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): ChapterRelationResponseCollection
  createdAt: DateTime
  data: Arc! @deprecated(reason: "Use root level fields instead")
  description: String
  documentId: ID!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  publishedAt: DateTime
  title: String!
  updatedAt: DateTime
}

type ArcEntityResponseCollection {
  data: [Arc!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [Arc!]!
  pageInfo: Pagination!
}

input ArcFiltersInput {
  and: [ArcFiltersInput]
  arc_id: StringFilterInput
  chapters: ChapterFiltersInput
  createdAt: DateTimeFilterInput
  description: StringFilterInput
  documentId: IDFilterInput
  locale: StringFilterInput
  localizations: ArcFiltersInput
  not: ArcFiltersInput
  or: [ArcFiltersInput]
  publishedAt: DateTimeFilterInput
  title: StringFilterInput
  updatedAt: DateTimeFilterInput
}

input ArcInput {
  arc_id: String
  chapters: [ID]
  description: String
  locale: String
  publishedAt: DateTime
  title: String
}

type Artifact {
  attributes: Artifact! @deprecated(reason: "Use root level fields instead")
  createdAt: DateTime
  data: Artifact! @deprecated(reason: "Use root level fields instead")
  description: String
  documentId: ID!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  model_file: UploadFile
  publishedAt: DateTime
  title: String
  updatedAt: DateTime
}

type ArtifactEntityResponseCollection {
  data: [Artifact!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [Artifact!]!
  pageInfo: Pagination!
}

input ArtifactFiltersInput {
  and: [ArtifactFiltersInput]
  createdAt: DateTimeFilterInput
  description: StringFilterInput
  documentId: IDFilterInput
  locale: StringFilterInput
  localizations: ArtifactFiltersInput
  not: ArtifactFiltersInput
  or: [ArtifactFiltersInput]
  publishedAt: DateTimeFilterInput
  title: StringFilterInput
  updatedAt: DateTimeFilterInput
}

input ArtifactInput {
  description: String
  locale: String
  model_file: ID
  publishedAt: DateTime
  title: String
}

input BooleanFilterInput {
  and: [Boolean]
  between: [Boolean]
  contains: Boolean
  containsi: Boolean
  endsWith: Boolean
  eq: Boolean
  eqi: Boolean
  gt: Boolean
  gte: Boolean
  in: [Boolean]
  lt: Boolean
  lte: Boolean
  ne: Boolean
  nei: Boolean
  not: BooleanFilterInput
  notContains: Boolean
  notContainsi: Boolean
  notIn: [Boolean]
  notNull: Boolean
  null: Boolean
  or: [Boolean]
  startsWith: Boolean
}

type Chapter {
  arc: Arc
  attributes: Chapter! @deprecated(reason: "Use root level fields instead")
  blurb: String
  chapter_header_media(filters: ComponentMultimediaHeaderMediaFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [ComponentMultimediaHeaderMedia]
  content: String
  createdAt: DateTime
  data: Chapter! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  emblem: UploadFile
  id: ID! @deprecated(reason: "Use `documentId` instead")
  interactive_blocks(filters: InteractiveBlockFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [InteractiveBlock]!
  interactive_blocks_connection(filters: InteractiveBlockFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): InteractiveBlockRelationResponseCollection
  publishedAt: DateTime
  seo_information: ComponentSeoSeoInformation
  slug: String
  title: String!
  updatedAt: DateTime
}

type ChapterEntityResponseCollection {
  data: [Chapter!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [Chapter!]!
  pageInfo: Pagination!
}

input ChapterFiltersInput {
  and: [ChapterFiltersInput]
  arc: ArcFiltersInput
  blurb: StringFilterInput
  chapter_header_media: ComponentMultimediaHeaderMediaFiltersInput
  content: StringFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  interactive_blocks: InteractiveBlockFiltersInput
  locale: StringFilterInput
  localizations: ChapterFiltersInput
  not: ChapterFiltersInput
  or: [ChapterFiltersInput]
  publishedAt: DateTimeFilterInput
  seo_information: ComponentSeoSeoInformationFiltersInput
  slug: StringFilterInput
  title: StringFilterInput
  updatedAt: DateTimeFilterInput
}

input ChapterInput {
  arc: ID
  blurb: String
  chapter_header_media: [ComponentMultimediaHeaderMediaInput]
  content: String
  emblem: ID
  interactive_blocks: [ID]
  locale: String
  publishedAt: DateTime
  seo_information: ComponentSeoSeoInformationInput
  slug: String
  title: String
}

type ChapterRelationResponseCollection {
  data: [Chapter!]! @deprecated(reason: "Use `nodes` field instead")
  nodes: [Chapter!]!
}

type Character {
  attributes: Character! @deprecated(reason: "Use root level fields instead")
  biography: String
  calling_card(filters: ComponentMultimediaCallingCardFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [ComponentMultimediaCallingCard]
  character_id: String
  character_quote: String
  createdAt: DateTime
  data: Character! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  epithets(filters: EpithetFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [Epithet]!
  epithets_connection(filters: EpithetFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): EpithetRelationResponseCollection
  faction: ENUM_CHARACTER_FACTION!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  laconic_description: String
  music_album: MusicAlbum
  name: String!
  profile_images(filters: UploadFileFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [UploadFile]!
  profile_images_connection(filters: UploadFileFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): UploadFileRelationResponseCollection
  publishedAt: DateTime
  updatedAt: DateTime
}

type CharacterEntityResponseCollection {
  data: [Character!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [Character!]!
  pageInfo: Pagination!
}

input CharacterFiltersInput {
  and: [CharacterFiltersInput]
  biography: StringFilterInput
  calling_card: ComponentMultimediaCallingCardFiltersInput
  character_id: StringFilterInput
  character_quote: StringFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  epithets: EpithetFiltersInput
  faction: StringFilterInput
  laconic_description: StringFilterInput
  locale: StringFilterInput
  localizations: CharacterFiltersInput
  music_album: MusicAlbumFiltersInput
  name: StringFilterInput
  not: CharacterFiltersInput
  or: [CharacterFiltersInput]
  publishedAt: DateTimeFilterInput
  updatedAt: DateTimeFilterInput
}

input CharacterInput {
  biography: String
  calling_card: [ComponentMultimediaCallingCardInput]
  character_id: String
  character_quote: String
  epithets: [ID]
  faction: ENUM_CHARACTER_FACTION
  laconic_description: String
  locale: String
  music_album: ID
  name: String
  profile_images: [ID]
  publishedAt: DateTime
}

type CharacterRelationResponseCollection {
  data: [Character!]! @deprecated(reason: "Use `nodes` field instead")
  nodes: [Character!]!
}

type ComponentMultimediaCallingCard {
  attributes: ComponentMultimediaCallingCard! @deprecated(reason: "Use root level fields instead")
  card_graphic: UploadFile
  data: ComponentMultimediaCallingCard! @deprecated(reason: "Use root level fields instead")
  date_given: Date
  greeting: String
  id: ID!
  title: String
}

input ComponentMultimediaCallingCardFiltersInput {
  and: [ComponentMultimediaCallingCardFiltersInput]
  date_given: DateFilterInput
  greeting: StringFilterInput
  not: ComponentMultimediaCallingCardFiltersInput
  or: [ComponentMultimediaCallingCardFiltersInput]
  title: StringFilterInput
}

input ComponentMultimediaCallingCardInput {
  card_graphic: ID
  date_given: Date
  greeting: String
  id: ID
  title: String
}

type ComponentMultimediaHeaderMedia {
  attributes: ComponentMultimediaHeaderMedia! @deprecated(reason: "Use root level fields instead")
  data: ComponentMultimediaHeaderMedia! @deprecated(reason: "Use root level fields instead")
  hero_carousel(filters: UploadFileFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [UploadFile]!
  hero_carousel_connection(filters: UploadFileFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): UploadFileRelationResponseCollection
  hero_image: UploadFile
  hero_video: UploadFile
  id: ID!
}

input ComponentMultimediaHeaderMediaFiltersInput {
  and: [ComponentMultimediaHeaderMediaFiltersInput]
  not: ComponentMultimediaHeaderMediaFiltersInput
  or: [ComponentMultimediaHeaderMediaFiltersInput]
}

input ComponentMultimediaHeaderMediaInput {
  hero_carousel: [ID]
  hero_image: ID
  hero_video: ID
  id: ID
}

type ComponentSeoSeoInformation {
  attributes: ComponentSeoSeoInformation! @deprecated(reason: "Use root level fields instead")
  data: ComponentSeoSeoInformation! @deprecated(reason: "Use root level fields instead")
  id: ID!
  language_code: String
  meta_description: String
  og_image: UploadFile
  og_site_name: String
  page_title: String
}

input ComponentSeoSeoInformationFiltersInput {
  and: [ComponentSeoSeoInformationFiltersInput]
  language_code: StringFilterInput
  meta_description: StringFilterInput
  not: ComponentSeoSeoInformationFiltersInput
  og_site_name: StringFilterInput
  or: [ComponentSeoSeoInformationFiltersInput]
  page_title: StringFilterInput
}

input ComponentSeoSeoInformationInput {
  id: ID
  language_code: String
  meta_description: String
  og_image: ID
  og_site_name: String
  page_title: String
}

"""
A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar Date

input DateFilterInput {
  and: [Date]
  between: [Date]
  contains: Date
  containsi: Date
  endsWith: Date
  eq: Date
  eqi: Date
  gt: Date
  gte: Date
  in: [Date]
  lt: Date
  lte: Date
  ne: Date
  nei: Date
  not: DateFilterInput
  notContains: Date
  notContainsi: Date
  notIn: [Date]
  notNull: Boolean
  null: Boolean
  or: [Date]
  startsWith: Date
}

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime

input DateTimeFilterInput {
  and: [DateTime]
  between: [DateTime]
  contains: DateTime
  containsi: DateTime
  endsWith: DateTime
  eq: DateTime
  eqi: DateTime
  gt: DateTime
  gte: DateTime
  in: [DateTime]
  lt: DateTime
  lte: DateTime
  ne: DateTime
  nei: DateTime
  not: DateTimeFilterInput
  notContains: DateTime
  notContainsi: DateTime
  notIn: [DateTime]
  notNull: Boolean
  null: Boolean
  or: [DateTime]
  startsWith: DateTime
}

type DeleteMutationResponse {
  documentId: ID!
}

enum ENUM_CHARACTER_FACTION {
  essence
  first_darkness
  golden_palanquin
  kingdom
  old_gods
  second_darkness
  third_darkness
}

enum ENUM_INTERACTIVEBLOCK_TYPE {
  standard_cascade
  standard_curtain
  standard_lightbox
  standard_poem
}

enum ENUM_MUSICALBUM_TYPE {
  extended_play
  long_play
  single
}

type Epithet {
  attributes: Epithet! @deprecated(reason: "Use root level fields instead")
  createdAt: DateTime
  data: Epithet! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  epithet_id: String
  id: ID! @deprecated(reason: "Use `documentId` instead")
  publishedAt: DateTime
  tagline: String
  title: String
  updatedAt: DateTime
}

type EpithetEntityResponseCollection {
  data: [Epithet!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [Epithet!]!
  pageInfo: Pagination!
}

input EpithetFiltersInput {
  and: [EpithetFiltersInput]
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  epithet_id: StringFilterInput
  locale: StringFilterInput
  localizations: EpithetFiltersInput
  not: EpithetFiltersInput
  or: [EpithetFiltersInput]
  publishedAt: DateTimeFilterInput
  tagline: StringFilterInput
  title: StringFilterInput
  updatedAt: DateTimeFilterInput
}

input EpithetInput {
  epithet_id: String
  locale: String
  publishedAt: DateTime
  tagline: String
  title: String
}

type EpithetRelationResponseCollection {
  data: [Epithet!]! @deprecated(reason: "Use `nodes` field instead")
  nodes: [Epithet!]!
}

input FileInfoInput {
  alternativeText: String
  caption: String
  name: String
}

input FloatFilterInput {
  and: [Float]
  between: [Float]
  contains: Float
  containsi: Float
  endsWith: Float
  eq: Float
  eqi: Float
  gt: Float
  gte: Float
  in: [Float]
  lt: Float
  lte: Float
  ne: Float
  nei: Float
  not: FloatFilterInput
  notContains: Float
  notContainsi: Float
  notIn: [Float]
  notNull: Boolean
  null: Boolean
  or: [Float]
  startsWith: Float
}

union GenericMorph = Arc | Artifact | Chapter | Character | ComponentMultimediaCallingCard | ComponentMultimediaHeaderMedia | ComponentSeoSeoInformation | Epithet | I18NLocale | InteractiveBlock | Location | MusicAlbum | ReviewWorkflowsWorkflow | ReviewWorkflowsWorkflowStage | Soundtrack | UploadFile | UsersPermissionsPermission | UsersPermissionsRole | UsersPermissionsUser

type I18NLocale {
  attributes: I18NLocale! @deprecated(reason: "Use root level fields instead")
  code: String
  createdAt: DateTime
  data: I18NLocale! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  name: String
  publishedAt: DateTime
  updatedAt: DateTime
}

type I18NLocaleEntityResponseCollection {
  data: [I18NLocale!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [I18NLocale!]!
  pageInfo: Pagination!
}

input I18NLocaleFiltersInput {
  and: [I18NLocaleFiltersInput]
  code: StringFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  locale: StringFilterInput
  localizations: I18NLocaleFiltersInput
  name: StringFilterInput
  not: I18NLocaleFiltersInput
  or: [I18NLocaleFiltersInput]
  publishedAt: DateTimeFilterInput
  updatedAt: DateTimeFilterInput
}

input IDFilterInput {
  and: [ID]
  between: [ID]
  contains: ID
  containsi: ID
  endsWith: ID
  eq: ID
  eqi: ID
  gt: ID
  gte: ID
  in: [ID]
  lt: ID
  lte: ID
  ne: ID
  nei: ID
  not: IDFilterInput
  notContains: ID
  notContainsi: ID
  notIn: [ID]
  notNull: Boolean
  null: Boolean
  or: [ID]
  startsWith: ID
}

input IntFilterInput {
  and: [Int]
  between: [Int]
  contains: Int
  containsi: Int
  endsWith: Int
  eq: Int
  eqi: Int
  gt: Int
  gte: Int
  in: [Int]
  lt: Int
  lte: Int
  ne: Int
  nei: Int
  not: IntFilterInput
  notContains: Int
  notContainsi: Int
  notIn: [Int]
  notNull: Boolean
  null: Boolean
  or: [Int]
  startsWith: Int
}

type InteractiveBlock {
  attributes: InteractiveBlock! @deprecated(reason: "Use root level fields instead")
  chapters(filters: ChapterFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [Chapter]!
  chapters_connection(filters: ChapterFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): ChapterRelationResponseCollection
  createdAt: DateTime
  data: InteractiveBlock! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  images(filters: UploadFileFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [UploadFile]!
  images_connection(filters: UploadFileFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): UploadFileRelationResponseCollection
  interactive_block_id: String!
  publishedAt: DateTime
  rich_text_caption: String
  sounds(filters: UploadFileFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [UploadFile]!
  sounds_connection(filters: UploadFileFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): UploadFileRelationResponseCollection
  soundtracks(filters: SoundtrackFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [Soundtrack]!
  soundtracks_connection(filters: SoundtrackFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): SoundtrackRelationResponseCollection
  title: String!
  type: ENUM_INTERACTIVEBLOCK_TYPE
  updatedAt: DateTime
}

type InteractiveBlockEntityResponseCollection {
  data: [InteractiveBlock!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [InteractiveBlock!]!
  pageInfo: Pagination!
}

input InteractiveBlockFiltersInput {
  and: [InteractiveBlockFiltersInput]
  chapters: ChapterFiltersInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  interactive_block_id: StringFilterInput
  locale: StringFilterInput
  localizations: InteractiveBlockFiltersInput
  not: InteractiveBlockFiltersInput
  or: [InteractiveBlockFiltersInput]
  publishedAt: DateTimeFilterInput
  rich_text_caption: StringFilterInput
  soundtracks: SoundtrackFiltersInput
  title: StringFilterInput
  type: StringFilterInput
  updatedAt: DateTimeFilterInput
}

input InteractiveBlockInput {
  chapters: [ID]
  images: [ID]
  interactive_block_id: String
  locale: String
  publishedAt: DateTime
  rich_text_caption: String
  sounds: [ID]
  soundtracks: [ID]
  title: String
  type: ENUM_INTERACTIVEBLOCK_TYPE
}

type InteractiveBlockRelationResponseCollection {
  data: [InteractiveBlock!]! @deprecated(reason: "Use `nodes` field instead")
  nodes: [InteractiveBlock!]!
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

input JSONFilterInput {
  and: [JSON]
  between: [JSON]
  contains: JSON
  containsi: JSON
  endsWith: JSON
  eq: JSON
  eqi: JSON
  gt: JSON
  gte: JSON
  in: [JSON]
  lt: JSON
  lte: JSON
  ne: JSON
  nei: JSON
  not: JSONFilterInput
  notContains: JSON
  notContainsi: JSON
  notIn: [JSON]
  notNull: Boolean
  null: Boolean
  or: [JSON]
  startsWith: JSON
}

type Location {
  attributes: Location! @deprecated(reason: "Use root level fields instead")
  createdAt: DateTime
  data: Location! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  geography: String
  history: String
  id: ID! @deprecated(reason: "Use `documentId` instead")
  laconic_description: String
  location_header_media: ComponentMultimediaHeaderMedia
  location_id: String
  music_album: MusicAlbum
  name: String
  present_in_main_story: Boolean
  publishedAt: DateTime
  updatedAt: DateTime
}

type LocationEntityResponseCollection {
  data: [Location!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [Location!]!
  pageInfo: Pagination!
}

input LocationFiltersInput {
  and: [LocationFiltersInput]
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  geography: StringFilterInput
  history: StringFilterInput
  laconic_description: StringFilterInput
  locale: StringFilterInput
  localizations: LocationFiltersInput
  location_header_media: ComponentMultimediaHeaderMediaFiltersInput
  location_id: StringFilterInput
  music_album: MusicAlbumFiltersInput
  name: StringFilterInput
  not: LocationFiltersInput
  or: [LocationFiltersInput]
  present_in_main_story: BooleanFilterInput
  publishedAt: DateTimeFilterInput
  updatedAt: DateTimeFilterInput
}

input LocationInput {
  geography: String
  history: String
  laconic_description: String
  locale: String
  location_header_media: ComponentMultimediaHeaderMediaInput
  location_id: String
  music_album: ID
  name: String
  present_in_main_story: Boolean
  publishedAt: DateTime
}

type LocationRelationResponseCollection {
  data: [Location!]! @deprecated(reason: "Use `nodes` field instead")
  nodes: [Location!]!
}

type MusicAlbum {
  attributes: MusicAlbum! @deprecated(reason: "Use root level fields instead")
  blurb: String
  characters(filters: CharacterFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [Character]!
  characters_connection(filters: CharacterFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): CharacterRelationResponseCollection
  cover_image: UploadFile
  createdAt: DateTime
  data: MusicAlbum! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  locations(filters: LocationFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [Location]!
  locations_connection(filters: LocationFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): LocationRelationResponseCollection
  music_album_id: String
  name: String!
  publishedAt: DateTime
  release_date: Date
  soundtracks(filters: SoundtrackFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [Soundtrack]!
  soundtracks_connection(filters: SoundtrackFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): SoundtrackRelationResponseCollection
  type: ENUM_MUSICALBUM_TYPE
  updatedAt: DateTime
}

type MusicAlbumEntityResponseCollection {
  data: [MusicAlbum!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [MusicAlbum!]!
  pageInfo: Pagination!
}

input MusicAlbumFiltersInput {
  and: [MusicAlbumFiltersInput]
  blurb: StringFilterInput
  characters: CharacterFiltersInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  locale: StringFilterInput
  localizations: MusicAlbumFiltersInput
  locations: LocationFiltersInput
  music_album_id: StringFilterInput
  name: StringFilterInput
  not: MusicAlbumFiltersInput
  or: [MusicAlbumFiltersInput]
  publishedAt: DateTimeFilterInput
  release_date: DateFilterInput
  soundtracks: SoundtrackFiltersInput
  type: StringFilterInput
  updatedAt: DateTimeFilterInput
}

input MusicAlbumInput {
  blurb: String
  characters: [ID]
  cover_image: ID
  locale: String
  locations: [ID]
  music_album_id: String
  name: String
  publishedAt: DateTime
  release_date: Date
  soundtracks: [ID]
  type: ENUM_MUSICALBUM_TYPE
}

type Mutation {
  """Change user password. Confirm with the current password."""
  changePassword(currentPassword: String!, password: String!, passwordConfirmation: String!): UsersPermissionsLoginPayload
  createArc(data: ArcInput!, status: PublicationStatus = PUBLISHED): Arc
  createArtifact(data: ArtifactInput!, status: PublicationStatus = PUBLISHED): Artifact
  createChapter(data: ChapterInput!, status: PublicationStatus = PUBLISHED): Chapter
  createCharacter(data: CharacterInput!, status: PublicationStatus = PUBLISHED): Character
  createEpithet(data: EpithetInput!, status: PublicationStatus = PUBLISHED): Epithet
  createInteractiveBlock(data: InteractiveBlockInput!, status: PublicationStatus = PUBLISHED): InteractiveBlock
  createLocation(data: LocationInput!, status: PublicationStatus = PUBLISHED): Location
  createMusicAlbum(data: MusicAlbumInput!, status: PublicationStatus = PUBLISHED): MusicAlbum
  createReviewWorkflowsWorkflow(data: ReviewWorkflowsWorkflowInput!, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflow
  createReviewWorkflowsWorkflowStage(data: ReviewWorkflowsWorkflowStageInput!, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflowStage
  createSoundtrack(data: SoundtrackInput!, status: PublicationStatus = PUBLISHED): Soundtrack

  """Create a new role"""
  createUsersPermissionsRole(data: UsersPermissionsRoleInput!): UsersPermissionsCreateRolePayload

  """Create a new user"""
  createUsersPermissionsUser(data: UsersPermissionsUserInput!): UsersPermissionsUserEntityResponse!
  deleteArc(documentId: ID!): DeleteMutationResponse
  deleteArtifact(documentId: ID!): DeleteMutationResponse
  deleteChapter(documentId: ID!): DeleteMutationResponse
  deleteCharacter(documentId: ID!): DeleteMutationResponse
  deleteEpithet(documentId: ID!): DeleteMutationResponse
  deleteInteractiveBlock(documentId: ID!): DeleteMutationResponse
  deleteLocation(documentId: ID!): DeleteMutationResponse
  deleteMusicAlbum(documentId: ID!): DeleteMutationResponse
  deleteReviewWorkflowsWorkflow(documentId: ID!): DeleteMutationResponse
  deleteReviewWorkflowsWorkflowStage(documentId: ID!): DeleteMutationResponse
  deleteSoundtrack(documentId: ID!): DeleteMutationResponse
  deleteUploadFile(id: ID!): UploadFile

  """Delete an existing role"""
  deleteUsersPermissionsRole(id: ID!): UsersPermissionsDeleteRolePayload

  """Delete an existing user"""
  deleteUsersPermissionsUser(id: ID!): UsersPermissionsUserEntityResponse!

  """Confirm an email users email address"""
  emailConfirmation(confirmation: String!): UsersPermissionsLoginPayload

  """Request a reset password token"""
  forgotPassword(email: String!): UsersPermissionsPasswordPayload
  login(input: UsersPermissionsLoginInput!): UsersPermissionsLoginPayload!

  """Register a user"""
  register(input: UsersPermissionsRegisterInput!): UsersPermissionsLoginPayload!

  """
  Reset user password. Confirm with a code (resetToken from forgotPassword)
  """
  resetPassword(code: String!, password: String!, passwordConfirmation: String!): UsersPermissionsLoginPayload
  updateArc(data: ArcInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): Arc
  updateArtifact(data: ArtifactInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): Artifact
  updateChapter(data: ChapterInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): Chapter
  updateCharacter(data: CharacterInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): Character
  updateEpithet(data: EpithetInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): Epithet
  updateInteractiveBlock(data: InteractiveBlockInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): InteractiveBlock
  updateLocation(data: LocationInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): Location
  updateMusicAlbum(data: MusicAlbumInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): MusicAlbum
  updateReviewWorkflowsWorkflow(data: ReviewWorkflowsWorkflowInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflow
  updateReviewWorkflowsWorkflowStage(data: ReviewWorkflowsWorkflowStageInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflowStage
  updateSoundtrack(data: SoundtrackInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): Soundtrack
  updateUploadFile(id: ID!, info: FileInfoInput): UploadFile!

  """Update an existing role"""
  updateUsersPermissionsRole(data: UsersPermissionsRoleInput!, id: ID!): UsersPermissionsUpdateRolePayload

  """Update an existing user"""
  updateUsersPermissionsUser(data: UsersPermissionsUserInput!, id: ID!): UsersPermissionsUserEntityResponse!
}

type Pagination {
  page: Int!
  pageCount: Int!
  pageSize: Int!
  total: Int!
}

input PaginationArg {
  limit: Int
  page: Int
  pageSize: Int
  start: Int
}

enum PublicationStatus {
  DRAFT
  PUBLISHED
}

type Query {
  arc(documentId: ID!, status: PublicationStatus = PUBLISHED): Arc
  arcs(filters: ArcFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [Arc]!
  arcs_connection(filters: ArcFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): ArcEntityResponseCollection
  artifact(documentId: ID!, status: PublicationStatus = PUBLISHED): Artifact
  artifacts(filters: ArtifactFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [Artifact]!
  artifacts_connection(filters: ArtifactFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): ArtifactEntityResponseCollection
  chapter(documentId: ID!, status: PublicationStatus = PUBLISHED): Chapter
  chapters(filters: ChapterFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [Chapter]!
  chapters_connection(filters: ChapterFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): ChapterEntityResponseCollection
  character(documentId: ID!, status: PublicationStatus = PUBLISHED): Character
  characters(filters: CharacterFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [Character]!
  characters_connection(filters: CharacterFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): CharacterEntityResponseCollection
  epithet(documentId: ID!, status: PublicationStatus = PUBLISHED): Epithet
  epithets(filters: EpithetFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [Epithet]!
  epithets_connection(filters: EpithetFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): EpithetEntityResponseCollection
  i18NLocale(documentId: ID!, status: PublicationStatus = PUBLISHED): I18NLocale
  i18NLocales(filters: I18NLocaleFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [I18NLocale]!
  i18NLocales_connection(filters: I18NLocaleFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): I18NLocaleEntityResponseCollection
  interactiveBlock(documentId: ID!, status: PublicationStatus = PUBLISHED): InteractiveBlock
  interactiveBlocks(filters: InteractiveBlockFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [InteractiveBlock]!
  interactiveBlocks_connection(filters: InteractiveBlockFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): InteractiveBlockEntityResponseCollection
  location(documentId: ID!, status: PublicationStatus = PUBLISHED): Location
  locations(filters: LocationFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [Location]!
  locations_connection(filters: LocationFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): LocationEntityResponseCollection
  me: UsersPermissionsMe
  musicAlbum(documentId: ID!, status: PublicationStatus = PUBLISHED): MusicAlbum
  musicAlbums(filters: MusicAlbumFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [MusicAlbum]!
  musicAlbums_connection(filters: MusicAlbumFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): MusicAlbumEntityResponseCollection
  reviewWorkflowsWorkflow(documentId: ID!, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflow
  reviewWorkflowsWorkflowStage(documentId: ID!, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflowStage
  reviewWorkflowsWorkflowStages(filters: ReviewWorkflowsWorkflowStageFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [ReviewWorkflowsWorkflowStage]!
  reviewWorkflowsWorkflowStages_connection(filters: ReviewWorkflowsWorkflowStageFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflowStageEntityResponseCollection
  reviewWorkflowsWorkflows(filters: ReviewWorkflowsWorkflowFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [ReviewWorkflowsWorkflow]!
  reviewWorkflowsWorkflows_connection(filters: ReviewWorkflowsWorkflowFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflowEntityResponseCollection
  soundtrack(documentId: ID!, status: PublicationStatus = PUBLISHED): Soundtrack
  soundtracks(filters: SoundtrackFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [Soundtrack]!
  soundtracks_connection(filters: SoundtrackFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): SoundtrackEntityResponseCollection
  uploadFile(documentId: ID!, status: PublicationStatus = PUBLISHED): UploadFile
  uploadFiles(filters: UploadFileFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [UploadFile]!
  uploadFiles_connection(filters: UploadFileFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): UploadFileEntityResponseCollection
  usersPermissionsRole(documentId: ID!, status: PublicationStatus = PUBLISHED): UsersPermissionsRole
  usersPermissionsRoles(filters: UsersPermissionsRoleFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [UsersPermissionsRole]!
  usersPermissionsRoles_connection(filters: UsersPermissionsRoleFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): UsersPermissionsRoleEntityResponseCollection
  usersPermissionsUser(documentId: ID!, status: PublicationStatus = PUBLISHED): UsersPermissionsUser
  usersPermissionsUsers(filters: UsersPermissionsUserFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): [UsersPermissionsUser]!
  usersPermissionsUsers_connection(filters: UsersPermissionsUserFiltersInput, pagination: PaginationArg = {}, sort: [String] = [], status: PublicationStatus = PUBLISHED): UsersPermissionsUserEntityResponseCollection
}

type ResponseCollectionMeta {
  pagination: Pagination!
}

type ReviewWorkflowsWorkflow {
  attributes: ReviewWorkflowsWorkflow! @deprecated(reason: "Use root level fields instead")
  contentTypes: JSON!
  createdAt: DateTime
  data: ReviewWorkflowsWorkflow! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  name: String!
  publishedAt: DateTime
  stages(filters: ReviewWorkflowsWorkflowStageFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [ReviewWorkflowsWorkflowStage]!
  stages_connection(filters: ReviewWorkflowsWorkflowStageFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): ReviewWorkflowsWorkflowStageRelationResponseCollection
  updatedAt: DateTime
}

type ReviewWorkflowsWorkflowEntityResponseCollection {
  data: [ReviewWorkflowsWorkflow!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [ReviewWorkflowsWorkflow!]!
  pageInfo: Pagination!
}

input ReviewWorkflowsWorkflowFiltersInput {
  and: [ReviewWorkflowsWorkflowFiltersInput]
  contentTypes: JSONFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  locale: StringFilterInput
  localizations: ReviewWorkflowsWorkflowFiltersInput
  name: StringFilterInput
  not: ReviewWorkflowsWorkflowFiltersInput
  or: [ReviewWorkflowsWorkflowFiltersInput]
  publishedAt: DateTimeFilterInput
  stages: ReviewWorkflowsWorkflowStageFiltersInput
  updatedAt: DateTimeFilterInput
}

input ReviewWorkflowsWorkflowInput {
  contentTypes: JSON
  locale: String
  name: String
  publishedAt: DateTime
  stages: [ID]
}

type ReviewWorkflowsWorkflowStage {
  attributes: ReviewWorkflowsWorkflowStage! @deprecated(reason: "Use root level fields instead")
  color: String
  createdAt: DateTime
  data: ReviewWorkflowsWorkflowStage! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  name: String
  publishedAt: DateTime
  updatedAt: DateTime
  workflow: ReviewWorkflowsWorkflow
}

type ReviewWorkflowsWorkflowStageEntityResponseCollection {
  data: [ReviewWorkflowsWorkflowStage!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [ReviewWorkflowsWorkflowStage!]!
  pageInfo: Pagination!
}

input ReviewWorkflowsWorkflowStageFiltersInput {
  and: [ReviewWorkflowsWorkflowStageFiltersInput]
  color: StringFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  locale: StringFilterInput
  localizations: ReviewWorkflowsWorkflowStageFiltersInput
  name: StringFilterInput
  not: ReviewWorkflowsWorkflowStageFiltersInput
  or: [ReviewWorkflowsWorkflowStageFiltersInput]
  publishedAt: DateTimeFilterInput
  updatedAt: DateTimeFilterInput
  workflow: ReviewWorkflowsWorkflowFiltersInput
}

input ReviewWorkflowsWorkflowStageInput {
  color: String
  locale: String
  name: String
  publishedAt: DateTime
  workflow: ID
}

type ReviewWorkflowsWorkflowStageRelationResponseCollection {
  data: [ReviewWorkflowsWorkflowStage!]! @deprecated(reason: "Use `nodes` field instead")
  nodes: [ReviewWorkflowsWorkflowStage!]!
}

type Soundtrack {
  attributes: Soundtrack! @deprecated(reason: "Use root level fields instead")
  createdAt: DateTime
  data: Soundtrack! @deprecated(reason: "Use root level fields instead")
  description: String
  documentId: ID!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  interactive_blocks(filters: InteractiveBlockFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [InteractiveBlock]!
  interactive_blocks_connection(filters: InteractiveBlockFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): InteractiveBlockRelationResponseCollection
  publishedAt: DateTime
  soundtrack_id: String
  title: String
  track_file: UploadFile
  updatedAt: DateTime
}

type SoundtrackEntityResponseCollection {
  data: [Soundtrack!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [Soundtrack!]!
  pageInfo: Pagination!
}

input SoundtrackFiltersInput {
  and: [SoundtrackFiltersInput]
  createdAt: DateTimeFilterInput
  description: StringFilterInput
  documentId: IDFilterInput
  interactive_blocks: InteractiveBlockFiltersInput
  locale: StringFilterInput
  localizations: SoundtrackFiltersInput
  not: SoundtrackFiltersInput
  or: [SoundtrackFiltersInput]
  publishedAt: DateTimeFilterInput
  soundtrack_id: StringFilterInput
  title: StringFilterInput
  updatedAt: DateTimeFilterInput
}

input SoundtrackInput {
  description: String
  interactive_blocks: [ID]
  locale: String
  publishedAt: DateTime
  soundtrack_id: String
  title: String
  track_file: ID
}

type SoundtrackRelationResponseCollection {
  data: [Soundtrack!]! @deprecated(reason: "Use `nodes` field instead")
  nodes: [Soundtrack!]!
}

input StringFilterInput {
  and: [String]
  between: [String]
  contains: String
  containsi: String
  endsWith: String
  eq: String
  eqi: String
  gt: String
  gte: String
  in: [String]
  lt: String
  lte: String
  ne: String
  nei: String
  not: StringFilterInput
  notContains: String
  notContainsi: String
  notIn: [String]
  notNull: Boolean
  null: Boolean
  or: [String]
  startsWith: String
}

type UploadFile {
  alternativeText: String
  attributes: UploadFile! @deprecated(reason: "Use root level fields instead")
  caption: String
  createdAt: DateTime
  data: UploadFile! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  ext: String
  formats: JSON
  hash: String!
  height: Int
  id: ID! @deprecated(reason: "Use `documentId` instead")
  mime: String!
  name: String!
  previewUrl: String
  provider: String!
  provider_metadata: JSON
  publishedAt: DateTime
  related: [GenericMorph]
  size: Float!
  updatedAt: DateTime
  url: String!
  width: Int
}

type UploadFileEntityResponseCollection {
  data: [UploadFile!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [UploadFile!]!
  pageInfo: Pagination!
}

input UploadFileFiltersInput {
  alternativeText: StringFilterInput
  and: [UploadFileFiltersInput]
  caption: StringFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  ext: StringFilterInput
  folderPath: StringFilterInput
  formats: JSONFilterInput
  hash: StringFilterInput
  height: IntFilterInput
  locale: StringFilterInput
  localizations: UploadFileFiltersInput
  mime: StringFilterInput
  name: StringFilterInput
  not: UploadFileFiltersInput
  or: [UploadFileFiltersInput]
  previewUrl: StringFilterInput
  provider: StringFilterInput
  provider_metadata: JSONFilterInput
  publishedAt: DateTimeFilterInput
  size: FloatFilterInput
  updatedAt: DateTimeFilterInput
  url: StringFilterInput
  width: IntFilterInput
}

type UploadFileRelationResponseCollection {
  data: [UploadFile!]! @deprecated(reason: "Use `nodes` field instead")
  nodes: [UploadFile!]!
}

type UsersPermissionsCreateRolePayload {
  ok: Boolean!
}

type UsersPermissionsDeleteRolePayload {
  ok: Boolean!
}

input UsersPermissionsLoginInput {
  identifier: String!
  password: String!
  provider: String! = "local"
}

type UsersPermissionsLoginPayload {
  jwt: String
  user: UsersPermissionsMe!
}

type UsersPermissionsMe {
  blocked: Boolean
  confirmed: Boolean
  email: String
  id: ID!
  role: UsersPermissionsMeRole
  username: String!
}

type UsersPermissionsMeRole {
  description: String
  id: ID!
  name: String!
  type: String
}

type UsersPermissionsPasswordPayload {
  ok: Boolean!
}

type UsersPermissionsPermission {
  action: String!
  attributes: UsersPermissionsPermission! @deprecated(reason: "Use root level fields instead")
  createdAt: DateTime
  data: UsersPermissionsPermission! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  publishedAt: DateTime
  role: UsersPermissionsRole
  updatedAt: DateTime
}

input UsersPermissionsPermissionFiltersInput {
  action: StringFilterInput
  and: [UsersPermissionsPermissionFiltersInput]
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  locale: StringFilterInput
  localizations: UsersPermissionsPermissionFiltersInput
  not: UsersPermissionsPermissionFiltersInput
  or: [UsersPermissionsPermissionFiltersInput]
  publishedAt: DateTimeFilterInput
  role: UsersPermissionsRoleFiltersInput
  updatedAt: DateTimeFilterInput
}

type UsersPermissionsPermissionRelationResponseCollection {
  data: [UsersPermissionsPermission!]! @deprecated(reason: "Use `nodes` field instead")
  nodes: [UsersPermissionsPermission!]!
}

input UsersPermissionsRegisterInput {
  email: String!
  password: String!
  username: String!
}

type UsersPermissionsRole {
  attributes: UsersPermissionsRole! @deprecated(reason: "Use root level fields instead")
  createdAt: DateTime
  data: UsersPermissionsRole! @deprecated(reason: "Use root level fields instead")
  description: String
  documentId: ID!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  name: String!
  permissions(filters: UsersPermissionsPermissionFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [UsersPermissionsPermission]!
  permissions_connection(filters: UsersPermissionsPermissionFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): UsersPermissionsPermissionRelationResponseCollection
  publishedAt: DateTime
  type: String
  updatedAt: DateTime
  users(filters: UsersPermissionsUserFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): [UsersPermissionsUser]!
  users_connection(filters: UsersPermissionsUserFiltersInput, pagination: PaginationArg = {}, sort: [String] = []): UsersPermissionsUserRelationResponseCollection
}

type UsersPermissionsRoleEntityResponseCollection {
  data: [UsersPermissionsRole!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [UsersPermissionsRole!]!
  pageInfo: Pagination!
}

input UsersPermissionsRoleFiltersInput {
  and: [UsersPermissionsRoleFiltersInput]
  createdAt: DateTimeFilterInput
  description: StringFilterInput
  documentId: IDFilterInput
  locale: StringFilterInput
  localizations: UsersPermissionsRoleFiltersInput
  name: StringFilterInput
  not: UsersPermissionsRoleFiltersInput
  or: [UsersPermissionsRoleFiltersInput]
  permissions: UsersPermissionsPermissionFiltersInput
  publishedAt: DateTimeFilterInput
  type: StringFilterInput
  updatedAt: DateTimeFilterInput
  users: UsersPermissionsUserFiltersInput
}

input UsersPermissionsRoleInput {
  description: String
  locale: String
  name: String
  permissions: [ID]
  publishedAt: DateTime
  type: String
  users: [ID]
}

type UsersPermissionsUpdateRolePayload {
  ok: Boolean!
}

type UsersPermissionsUser {
  attributes: UsersPermissionsUser! @deprecated(reason: "Use root level fields instead")
  blocked: Boolean
  confirmed: Boolean
  createdAt: DateTime
  data: UsersPermissionsUser! @deprecated(reason: "Use root level fields instead")
  documentId: ID!
  email: String!
  id: ID! @deprecated(reason: "Use `documentId` instead")
  provider: String
  publishedAt: DateTime
  role: UsersPermissionsRole
  updatedAt: DateTime
  username: String!
}

type UsersPermissionsUserEntityResponse {
  data: UsersPermissionsUser
}

type UsersPermissionsUserEntityResponseCollection {
  data: [UsersPermissionsUser!]! @deprecated(reason: "Use `nodes` field instead")
  meta: ResponseCollectionMeta! @deprecated(reason: "Use the `pageInfo` field instead")
  nodes: [UsersPermissionsUser!]!
  pageInfo: Pagination!
}

input UsersPermissionsUserFiltersInput {
  and: [UsersPermissionsUserFiltersInput]
  blocked: BooleanFilterInput
  confirmationToken: StringFilterInput
  confirmed: BooleanFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  email: StringFilterInput
  locale: StringFilterInput
  localizations: UsersPermissionsUserFiltersInput
  not: UsersPermissionsUserFiltersInput
  or: [UsersPermissionsUserFiltersInput]
  password: StringFilterInput
  provider: StringFilterInput
  publishedAt: DateTimeFilterInput
  resetPasswordToken: StringFilterInput
  role: UsersPermissionsRoleFiltersInput
  updatedAt: DateTimeFilterInput
  username: StringFilterInput
}

input UsersPermissionsUserInput {
  blocked: Boolean
  confirmationToken: String
  confirmed: Boolean
  email: String
  locale: String
  password: String
  provider: String
  publishedAt: DateTime
  resetPasswordToken: String
  role: ID
  username: String
}

type UsersPermissionsUserRelationResponseCollection {
  data: [UsersPermissionsUser!]! @deprecated(reason: "Use `nodes` field instead")
  nodes: [UsersPermissionsUser!]!
}
