<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 BadgeMod.glb -t
-->

<!-- Make sure to utilize the options from this utility command:  -->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Badge_1: THREE.Mesh
      Badge_2: THREE.Mesh
      Badge_3: THREE.Mesh
    }
    materials: {
      Rest: THREE.MeshStandardMaterial
      Inner: THREE.MeshStandardMaterial
      Ring: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('src/lib/components/threlte/BadgeMod.glb')
    // Update the path to the glTF file after generating the Svelte component via the utility command

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Badge_1.geometry} material={gltf.materials.Rest} />
    <T.Mesh geometry={gltf.nodes.Badge_2.geometry} material={gltf.materials.Inner} />
    <T.Mesh geometry={gltf.nodes.Badge_3.geometry} material={gltf.materials.Ring} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
