query IndividualChapterQuery($chapter_id: String!) {
  chapters(filters: { slug: { eq: $chapter_id }}) {
    data {
      id
      attributes {
        title
        content
        slug
        chapter_header_media {
          id,
          hero_image {
            data {
              id,
              attributes {
                url
              }
            }
          }
        }
      }
    }
  }
}