query X {
  chapters {
    data {
      id
      attributes {
        title
        slug
      }
    }
    meta {
      pagination {
        page
        pageSize
        total
        pageCount
      }
    }
  }
}
