# query getAllSoundtracks {
#   soundtracks
#   {
# 		data {
#       attributes
#       {
#         soundtrack_id
#         track_file {
#           data {
#             attributes
#             {url}
#           }
#         }
#       }
#     }
#   }
# }

query getAllSoundtracks {
  soundtracks {
    soundtrack_id
    track_file {
      url
    }
  }
}
