query getAllSoundtracks {
  soundtracks
  {
		data {
      attributes
      {
        soundtrack_id
        track_file {
          data {
            attributes
            {url}
          }
        }
      }
    }
  }
}