query GetIndividualChapter($chapter_id: String!) {
  chapters(filters: { slug: { eq: $chapter_id } }) {
    title
    blurb
    content
    slug
    emblem {
      url
    }
    chapter_header_media {
      hero_image {
        url
      }
    }
    interactive_blocks {
      title
      type
      interactive_block_id
      rich_text_caption
      sounds {
        url
      }
      images {
        url
      }
    }
  }
}
