query GetIndividualChapter($chapter_id: String!) {
  chapters(filters: { slug: { eq: $chapter_id } }) {
    data {
      id
      attributes {
        title
        blurb
        content
        slug
        chapter_header_media {
          id
          hero_image {
            data {
              id
              attributes {
                url
              }
            }
          }
        }
        interactive_blocks {
          data {
            id
            attributes {
              title
              type
              interactive_block_id
              rich_text_caption
              sounds {
                data {
                  attributes {
                    url
                  }
                }
              }
              images {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
