query SoundtracksInBlockQuery ($id: String!) {
  interactiveBlocks (filters: { interactive_block_id: { eq: $id }}) {
    data
    {
      id
      attributes
      {
        interactive_block_id,
        characters {
          data {
            id,
            attributes {
              name
            }
          }
        }
        artifacts {
          data {
            attributes {
              title
            }
          }
        }
        soundtracks {
          data {
            id
            attributes
            {
              soundtrack_id,
              title,
              track_file
              {
                data {
                  attributes
                  {
                  	url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}